yarnPath: .yarn/releases/yarn-4.4.1.cjs
enableGlobalCache: false

packageExtensions:
  "local-pkg@*":
    dependencies:
      "happy-dom": "^12.5.0"
  "swiper@*":
    dependencies:
      "react": "^18.2.0"
  "@aws-sdk/core@*":
    dependencies:
      "tslib": "*"
